services:
  db:
    image: postgres:13
    volumes:
      - rbb_db:/var/lib/postgresql/data
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      appnet:
        aliases: ["rbb-db"]

  rbb:
    image: rbb_bot:latest
    restart: "unless-stopped"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      DB_URL: "${DB_URL}"
    networks: [appnet]

volumes:
  rbb_db:
    name: "rbb_db"

networks:
  appnet:
