
services:
  db:
    image: postgres:13
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
  rbb:
    image: rbb:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./rbb_bot:/app/rbb_bot
    depends_on: 
      - "db"
    environment:
      - PYTHONUNBUFFERED=1
